version: "3.2"

services:
  node:
    container_name: node-lunes
    build: .
    ports:
      - "9944:9944"
    volumes:
      - .:/var/www/lunes-nightly
    #command: bash -c "ls && ./lunes-node --dev --ws-external"
    command: bash -c "./lunes-node --chain  lunes-staging-raw.json -d /data/validator --name validator2 --validator --port 30333 --ws-port 9944 --rpc-port 9933"
