version: "3.2"

services:
  dev:
    container_name: node-lunes
    build: .
    environment:
      - CARGO_HOME=/.cargo
    ports:
      - "9944:9944"
    volumes:
      - .:/var/www/lunes-nightly
    command: bash -c "ls && ./lunes-node --dev --ws-external"
