[package]
authors = ["Lunes"]
build = "build.rs"
description = "A fresh FRAME-based Substrate node, ready for hacking."
edition = "2021"
homepage = "https://substrate.io/"
license = "Unlicense"
name = "lunes-node"
publish = false
repository = "https://github.com/substrate-developer-hub/substrate-node-template/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "lunes-node"

[dependencies]
clap = { version = "4.0.9", features = ["derive"] }
futures = { version = "0.3.21", features = ["thread-pool"]}
serde_json = "1.0.85"

sc-cli = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sc-executor = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sc-service = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sc-telemetry = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sc-keystore = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sc-transaction-pool = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sc-consensus-aura = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sp-consensus-aura = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sp-consensus = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sc-consensus = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sc-consensus-grandpa = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sp-consensus-grandpa = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sc-client-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sp-timestamp = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sp-inherents = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sp-keyring = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
pallet-transaction-payment = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }

# These dependencies are used for the node template's RPCs
jsonrpsee = { version = "0.24.8", features = ["server"] }
sc-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sp-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sc-rpc-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sp-blockchain = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sp-block-builder = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
sc-basic-authorship = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }

# Local Dependencies
lunes-runtime = { version = "4.0.0-dev", path = "../runtime" }
node-primitives = { version = "2.0.0", path = "../primitives" }

# CLI-specific dependencies
try-runtime-cli = { optional = true, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2412" }

[features]
default = []
# Dependencies that are only required if runtime benchmarking should be build.
runtime-benchmarks = [
    "lunes-runtime/runtime-benchmarks",
    "frame-benchmarking/runtime-benchmarks",
    "frame-benchmarking-cli/runtime-benchmarks",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = ["lunes-runtime/try-runtime", "try-runtime-cli/try-runtime"]
